obj/CivetServer.$(OBJ_EXT): src/CivetServer.cpp  inc/CivetServer.h
obj/MemoryMapped.$(OBJ_EXT): src/MemoryMapped.cpp  inc/MemoryMapped.h
obj/civetweb.$(OBJ_EXT): src/civetweb.c  inc/civetweb.h
obj/civetweb.$(OBJ_EXT): src/civetweb.c  src/handle_form.inl
obj/civetweb.$(OBJ_EXT): src/civetweb.c  src/md5.inl
obj/civetweb.$(OBJ_EXT): src/civetweb.c  src/mod_lua.inl
obj/civetweb.$(OBJ_EXT): src/civetweb.c  src/sha1.inl
obj/civetweb.$(OBJ_EXT): src/civetweb.c  src/timer.inl
obj/ck_nesting.$(OBJ_EXT): src/ck_nesting.cpp  inc/ck_nesting.h
obj/embedded_cpp.$(OBJ_EXT): src/embedded_cpp.cpp  inc/CivetServer.h
obj/embedded_cpp.$(OBJ_EXT): src/embedded_cpp.cpp  inc/perf_event_subset.h
obj/embedded_cpp.$(OBJ_EXT): src/embedded_cpp.cpp  inc/utils.h
obj/embedded_cpp.$(OBJ_EXT): src/embedded_cpp.cpp  inc/utils2.h
obj/embedded_cpp.$(OBJ_EXT): src/embedded_cpp.cpp  inc/web_api.h
obj/etw_parse.$(OBJ_EXT): src/etw_parse.cpp  inc/etw_parse.h
obj/etw_parse.$(OBJ_EXT): src/etw_parse.cpp  inc/lua_rtns.h
obj/etw_parse.$(OBJ_EXT): src/etw_parse.cpp  inc/oppat.h
obj/etw_parse.$(OBJ_EXT): src/etw_parse.cpp  inc/perf_event_subset.h
obj/etw_parse.$(OBJ_EXT): src/etw_parse.cpp  inc/printf.h
obj/etw_parse.$(OBJ_EXT): src/etw_parse.cpp  inc/pugixml.hpp
obj/etw_parse.$(OBJ_EXT): src/etw_parse.cpp  inc/rd_json.h
obj/etw_parse.$(OBJ_EXT): src/etw_parse.cpp  inc/rd_json2.h
obj/etw_parse.$(OBJ_EXT): src/etw_parse.cpp  inc/utils.h
obj/etw_parse.$(OBJ_EXT): src/etw_parse.cpp  inc/utils2.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/lapi.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/ldebug.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/ldo.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/lfunc.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/lgc.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/lmem.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/lobject.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/lprefix.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/lstate.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/lstring.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/ltable.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/ltm.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/lua.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/lundump.h
obj/lua/lapi.$(OBJ_EXT): src/lua/lapi.c  src/lua/lvm.h
obj/lua/lapi.h: src/lua/lapi.h  src/lua/llimits.h
obj/lua/lapi.h: src/lua/lapi.h  src/lua/lstate.h
obj/lua/lauxlib.$(OBJ_EXT): src/lua/lauxlib.c  src/lua/lauxlib.h
obj/lua/lauxlib.$(OBJ_EXT): src/lua/lauxlib.c  src/lua/lprefix.h
obj/lua/lauxlib.$(OBJ_EXT): src/lua/lauxlib.c  src/lua/lua.h
obj/lua/lauxlib.h: src/lua/lauxlib.h  src/lua/lua.h
obj/lua/lbaselib.$(OBJ_EXT): src/lua/lbaselib.c  src/lua/lauxlib.h
obj/lua/lbaselib.$(OBJ_EXT): src/lua/lbaselib.c  src/lua/lprefix.h
obj/lua/lbaselib.$(OBJ_EXT): src/lua/lbaselib.c  src/lua/lua.h
obj/lua/lbaselib.$(OBJ_EXT): src/lua/lbaselib.c  src/lua/lualib.h
obj/lua/lbitlib.$(OBJ_EXT): src/lua/lbitlib.c  src/lua/lauxlib.h
obj/lua/lbitlib.$(OBJ_EXT): src/lua/lbitlib.c  src/lua/lprefix.h
obj/lua/lbitlib.$(OBJ_EXT): src/lua/lbitlib.c  src/lua/lua.h
obj/lua/lbitlib.$(OBJ_EXT): src/lua/lbitlib.c  src/lua/lualib.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/lcode.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/ldebug.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/ldo.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/lgc.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/llex.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/lmem.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/lobject.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/lopcodes.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/lparser.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/lprefix.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/lstring.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/ltable.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/lua.h
obj/lua/lcode.$(OBJ_EXT): src/lua/lcode.c  src/lua/lvm.h
obj/lua/lcode.h: src/lua/lcode.h  src/lua/llex.h
obj/lua/lcode.h: src/lua/lcode.h  src/lua/lobject.h
obj/lua/lcode.h: src/lua/lcode.h  src/lua/lopcodes.h
obj/lua/lcode.h: src/lua/lcode.h  src/lua/lparser.h
obj/lua/lcorolib.$(OBJ_EXT): src/lua/lcorolib.c  src/lua/lauxlib.h
obj/lua/lcorolib.$(OBJ_EXT): src/lua/lcorolib.c  src/lua/lprefix.h
obj/lua/lcorolib.$(OBJ_EXT): src/lua/lcorolib.c  src/lua/lua.h
obj/lua/lcorolib.$(OBJ_EXT): src/lua/lcorolib.c  src/lua/lualib.h
obj/lua/lctype.$(OBJ_EXT): src/lua/lctype.c  src/lua/lctype.h
obj/lua/lctype.$(OBJ_EXT): src/lua/lctype.c  src/lua/lprefix.h
obj/lua/lctype.h: src/lua/lctype.h  src/lua/llimits.h
obj/lua/lctype.h: src/lua/lctype.h  src/lua/lua.h
obj/lua/ldblib.$(OBJ_EXT): src/lua/ldblib.c  src/lua/lauxlib.h
obj/lua/ldblib.$(OBJ_EXT): src/lua/ldblib.c  src/lua/lprefix.h
obj/lua/ldblib.$(OBJ_EXT): src/lua/ldblib.c  src/lua/lua.h
obj/lua/ldblib.$(OBJ_EXT): src/lua/ldblib.c  src/lua/lualib.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/lapi.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/lcode.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/ldebug.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/ldo.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/lfunc.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/lobject.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/lopcodes.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/lprefix.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/lstate.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/lstring.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/ltable.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/ltm.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/lua.h
obj/lua/ldebug.$(OBJ_EXT): src/lua/ldebug.c  src/lua/lvm.h
obj/lua/ldebug.h: src/lua/ldebug.h  src/lua/lstate.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lapi.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/ldebug.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/ldo.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lfunc.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lgc.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lmem.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lobject.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lopcodes.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lparser.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lprefix.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lstate.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lstring.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/ltable.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/ltm.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lua.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lundump.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lvm.h
obj/lua/ldo.$(OBJ_EXT): src/lua/ldo.c  src/lua/lzio.h
obj/lua/ldo.h: src/lua/ldo.h  src/lua/lobject.h
obj/lua/ldo.h: src/lua/ldo.h  src/lua/lstate.h
obj/lua/ldo.h: src/lua/ldo.h  src/lua/lzio.h
obj/lua/ldump.$(OBJ_EXT): src/lua/ldump.c  src/lua/lobject.h
obj/lua/ldump.$(OBJ_EXT): src/lua/ldump.c  src/lua/lprefix.h
obj/lua/ldump.$(OBJ_EXT): src/lua/ldump.c  src/lua/lstate.h
obj/lua/ldump.$(OBJ_EXT): src/lua/ldump.c  src/lua/lua.h
obj/lua/ldump.$(OBJ_EXT): src/lua/ldump.c  src/lua/lundump.h
obj/lua/lfunc.$(OBJ_EXT): src/lua/lfunc.c  src/lua/lfunc.h
obj/lua/lfunc.$(OBJ_EXT): src/lua/lfunc.c  src/lua/lgc.h
obj/lua/lfunc.$(OBJ_EXT): src/lua/lfunc.c  src/lua/lmem.h
obj/lua/lfunc.$(OBJ_EXT): src/lua/lfunc.c  src/lua/lobject.h
obj/lua/lfunc.$(OBJ_EXT): src/lua/lfunc.c  src/lua/lprefix.h
obj/lua/lfunc.$(OBJ_EXT): src/lua/lfunc.c  src/lua/lstate.h
obj/lua/lfunc.$(OBJ_EXT): src/lua/lfunc.c  src/lua/lua.h
obj/lua/lfunc.h: src/lua/lfunc.h  src/lua/lobject.h
obj/lua/lgc.$(OBJ_EXT): src/lua/lgc.c  src/lua/ldebug.h
obj/lua/lgc.$(OBJ_EXT): src/lua/lgc.c  src/lua/ldo.h
obj/lua/lgc.$(OBJ_EXT): src/lua/lgc.c  src/lua/lfunc.h
obj/lua/lgc.$(OBJ_EXT): src/lua/lgc.c  src/lua/lgc.h
obj/lua/lgc.$(OBJ_EXT): src/lua/lgc.c  src/lua/lmem.h
obj/lua/lgc.$(OBJ_EXT): src/lua/lgc.c  src/lua/lobject.h
obj/lua/lgc.$(OBJ_EXT): src/lua/lgc.c  src/lua/lprefix.h
obj/lua/lgc.$(OBJ_EXT): src/lua/lgc.c  src/lua/lstate.h
obj/lua/lgc.$(OBJ_EXT): src/lua/lgc.c  src/lua/lstring.h
obj/lua/lgc.$(OBJ_EXT): src/lua/lgc.c  src/lua/ltable.h
obj/lua/lgc.$(OBJ_EXT): src/lua/lgc.c  src/lua/ltm.h
obj/lua/lgc.$(OBJ_EXT): src/lua/lgc.c  src/lua/lua.h
obj/lua/lgc.h: src/lua/lgc.h  src/lua/lobject.h
obj/lua/lgc.h: src/lua/lgc.h  src/lua/lstate.h
obj/lua/linit.$(OBJ_EXT): src/lua/linit.c  src/lua/lauxlib.h
obj/lua/linit.$(OBJ_EXT): src/lua/linit.c  src/lua/lprefix.h
obj/lua/linit.$(OBJ_EXT): src/lua/linit.c  src/lua/lua.h
obj/lua/linit.$(OBJ_EXT): src/lua/linit.c  src/lua/lualib.h
obj/lua/liolib.$(OBJ_EXT): src/lua/liolib.c  src/lua/lauxlib.h
obj/lua/liolib.$(OBJ_EXT): src/lua/liolib.c  src/lua/lprefix.h
obj/lua/liolib.$(OBJ_EXT): src/lua/liolib.c  src/lua/lua.h
obj/lua/liolib.$(OBJ_EXT): src/lua/liolib.c  src/lua/lualib.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/lctype.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/ldebug.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/ldo.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/lgc.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/llex.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/lobject.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/lparser.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/lprefix.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/lstate.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/lstring.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/ltable.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/lua.h
obj/lua/llex.$(OBJ_EXT): src/lua/llex.c  src/lua/lzio.h
obj/lua/llex.h: src/lua/llex.h  src/lua/lobject.h
obj/lua/llex.h: src/lua/llex.h  src/lua/lzio.h
obj/lua/llimits.h: src/lua/llimits.h  src/lua/lua.h
obj/lua/lmathlib.$(OBJ_EXT): src/lua/lmathlib.c  src/lua/lauxlib.h
obj/lua/lmathlib.$(OBJ_EXT): src/lua/lmathlib.c  src/lua/lprefix.h
obj/lua/lmathlib.$(OBJ_EXT): src/lua/lmathlib.c  src/lua/lua.h
obj/lua/lmathlib.$(OBJ_EXT): src/lua/lmathlib.c  src/lua/lualib.h
obj/lua/lmem.$(OBJ_EXT): src/lua/lmem.c  src/lua/ldebug.h
obj/lua/lmem.$(OBJ_EXT): src/lua/lmem.c  src/lua/ldo.h
obj/lua/lmem.$(OBJ_EXT): src/lua/lmem.c  src/lua/lgc.h
obj/lua/lmem.$(OBJ_EXT): src/lua/lmem.c  src/lua/lmem.h
obj/lua/lmem.$(OBJ_EXT): src/lua/lmem.c  src/lua/lobject.h
obj/lua/lmem.$(OBJ_EXT): src/lua/lmem.c  src/lua/lprefix.h
obj/lua/lmem.$(OBJ_EXT): src/lua/lmem.c  src/lua/lstate.h
obj/lua/lmem.$(OBJ_EXT): src/lua/lmem.c  src/lua/lua.h
obj/lua/lmem.h: src/lua/lmem.h  src/lua/llimits.h
obj/lua/lmem.h: src/lua/lmem.h  src/lua/lua.h
obj/lua/loadlib.$(OBJ_EXT): src/lua/loadlib.c  src/lua/lauxlib.h
obj/lua/loadlib.$(OBJ_EXT): src/lua/loadlib.c  src/lua/lprefix.h
obj/lua/loadlib.$(OBJ_EXT): src/lua/loadlib.c  src/lua/lua.h
obj/lua/loadlib.$(OBJ_EXT): src/lua/loadlib.c  src/lua/lualib.h
obj/lua/lobject.$(OBJ_EXT): src/lua/lobject.c  src/lua/lctype.h
obj/lua/lobject.$(OBJ_EXT): src/lua/lobject.c  src/lua/ldebug.h
obj/lua/lobject.$(OBJ_EXT): src/lua/lobject.c  src/lua/ldo.h
obj/lua/lobject.$(OBJ_EXT): src/lua/lobject.c  src/lua/lmem.h
obj/lua/lobject.$(OBJ_EXT): src/lua/lobject.c  src/lua/lobject.h
obj/lua/lobject.$(OBJ_EXT): src/lua/lobject.c  src/lua/lprefix.h
obj/lua/lobject.$(OBJ_EXT): src/lua/lobject.c  src/lua/lstate.h
obj/lua/lobject.$(OBJ_EXT): src/lua/lobject.c  src/lua/lstring.h
obj/lua/lobject.$(OBJ_EXT): src/lua/lobject.c  src/lua/lua.h
obj/lua/lobject.$(OBJ_EXT): src/lua/lobject.c  src/lua/lvm.h
obj/lua/lobject.h: src/lua/lobject.h  src/lua/llimits.h
obj/lua/lobject.h: src/lua/lobject.h  src/lua/lua.h
obj/lua/lopcodes.$(OBJ_EXT): src/lua/lopcodes.c  src/lua/lopcodes.h
obj/lua/lopcodes.$(OBJ_EXT): src/lua/lopcodes.c  src/lua/lprefix.h
obj/lua/lopcodes.h: src/lua/lopcodes.h  src/lua/llimits.h
obj/lua/loslib.$(OBJ_EXT): src/lua/loslib.c  src/lua/lauxlib.h
obj/lua/loslib.$(OBJ_EXT): src/lua/loslib.c  src/lua/lprefix.h
obj/lua/loslib.$(OBJ_EXT): src/lua/loslib.c  src/lua/lua.h
obj/lua/loslib.$(OBJ_EXT): src/lua/loslib.c  src/lua/lualib.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/lcode.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/ldebug.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/ldo.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/lfunc.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/llex.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/lmem.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/lobject.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/lopcodes.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/lparser.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/lprefix.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/lstate.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/lstring.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/ltable.h
obj/lua/lparser.$(OBJ_EXT): src/lua/lparser.c  src/lua/lua.h
obj/lua/lparser.h: src/lua/lparser.h  src/lua/llimits.h
obj/lua/lparser.h: src/lua/lparser.h  src/lua/lobject.h
obj/lua/lparser.h: src/lua/lparser.h  src/lua/lzio.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/lapi.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/ldebug.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/ldo.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/lfunc.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/lgc.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/llex.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/lmem.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/lprefix.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/lstate.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/lstring.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/ltable.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/ltm.h
obj/lua/lstate.$(OBJ_EXT): src/lua/lstate.c  src/lua/lua.h
obj/lua/lstate.h: src/lua/lstate.h  src/lua/lobject.h
obj/lua/lstate.h: src/lua/lstate.h  src/lua/ltm.h
obj/lua/lstate.h: src/lua/lstate.h  src/lua/lua.h
obj/lua/lstate.h: src/lua/lstate.h  src/lua/lzio.h
obj/lua/lstring.$(OBJ_EXT): src/lua/lstring.c  src/lua/ldebug.h
obj/lua/lstring.$(OBJ_EXT): src/lua/lstring.c  src/lua/ldo.h
obj/lua/lstring.$(OBJ_EXT): src/lua/lstring.c  src/lua/lmem.h
obj/lua/lstring.$(OBJ_EXT): src/lua/lstring.c  src/lua/lobject.h
obj/lua/lstring.$(OBJ_EXT): src/lua/lstring.c  src/lua/lprefix.h
obj/lua/lstring.$(OBJ_EXT): src/lua/lstring.c  src/lua/lstate.h
obj/lua/lstring.$(OBJ_EXT): src/lua/lstring.c  src/lua/lstring.h
obj/lua/lstring.$(OBJ_EXT): src/lua/lstring.c  src/lua/lua.h
obj/lua/lstring.h: src/lua/lstring.h  src/lua/lgc.h
obj/lua/lstring.h: src/lua/lstring.h  src/lua/lobject.h
obj/lua/lstring.h: src/lua/lstring.h  src/lua/lstate.h
obj/lua/lstrlib.$(OBJ_EXT): src/lua/lstrlib.c  src/lua/lauxlib.h
obj/lua/lstrlib.$(OBJ_EXT): src/lua/lstrlib.c  src/lua/lprefix.h
obj/lua/lstrlib.$(OBJ_EXT): src/lua/lstrlib.c  src/lua/lua.h
obj/lua/lstrlib.$(OBJ_EXT): src/lua/lstrlib.c  src/lua/lualib.h
obj/lua/ltable.$(OBJ_EXT): src/lua/ltable.c  src/lua/ldebug.h
obj/lua/ltable.$(OBJ_EXT): src/lua/ltable.c  src/lua/ldo.h
obj/lua/ltable.$(OBJ_EXT): src/lua/ltable.c  src/lua/lgc.h
obj/lua/ltable.$(OBJ_EXT): src/lua/ltable.c  src/lua/lmem.h
obj/lua/ltable.$(OBJ_EXT): src/lua/ltable.c  src/lua/lobject.h
obj/lua/ltable.$(OBJ_EXT): src/lua/ltable.c  src/lua/lprefix.h
obj/lua/ltable.$(OBJ_EXT): src/lua/ltable.c  src/lua/lstate.h
obj/lua/ltable.$(OBJ_EXT): src/lua/ltable.c  src/lua/lstring.h
obj/lua/ltable.$(OBJ_EXT): src/lua/ltable.c  src/lua/ltable.h
obj/lua/ltable.$(OBJ_EXT): src/lua/ltable.c  src/lua/lua.h
obj/lua/ltable.$(OBJ_EXT): src/lua/ltable.c  src/lua/lvm.h
obj/lua/ltable.h: src/lua/ltable.h  src/lua/lobject.h
obj/lua/ltablib.$(OBJ_EXT): src/lua/ltablib.c  src/lua/lauxlib.h
obj/lua/ltablib.$(OBJ_EXT): src/lua/ltablib.c  src/lua/lprefix.h
obj/lua/ltablib.$(OBJ_EXT): src/lua/ltablib.c  src/lua/lua.h
obj/lua/ltablib.$(OBJ_EXT): src/lua/ltablib.c  src/lua/lualib.h
obj/lua/ltm.$(OBJ_EXT): src/lua/ltm.c  src/lua/ldebug.h
obj/lua/ltm.$(OBJ_EXT): src/lua/ltm.c  src/lua/ldo.h
obj/lua/ltm.$(OBJ_EXT): src/lua/ltm.c  src/lua/lobject.h
obj/lua/ltm.$(OBJ_EXT): src/lua/ltm.c  src/lua/lprefix.h
obj/lua/ltm.$(OBJ_EXT): src/lua/ltm.c  src/lua/lstate.h
obj/lua/ltm.$(OBJ_EXT): src/lua/ltm.c  src/lua/lstring.h
obj/lua/ltm.$(OBJ_EXT): src/lua/ltm.c  src/lua/ltable.h
obj/lua/ltm.$(OBJ_EXT): src/lua/ltm.c  src/lua/ltm.h
obj/lua/ltm.$(OBJ_EXT): src/lua/ltm.c  src/lua/lua.h
obj/lua/ltm.$(OBJ_EXT): src/lua/ltm.c  src/lua/lvm.h
obj/lua/ltm.h: src/lua/ltm.h  src/lua/lobject.h
obj/lua/lua.h: src/lua/lua.h  src/lua/luaconf.h
obj/lua/lua.hpp: src/lua/lua.hpp  src/lua/lauxlib.h
obj/lua/lua.hpp: src/lua/lua.hpp  src/lua/lua.h
obj/lua/lua.hpp: src/lua/lua.hpp  src/lua/lualib.h
obj/lua/lualib.h: src/lua/lualib.h  src/lua/lua.h
obj/lua/lundump.$(OBJ_EXT): src/lua/lundump.c  src/lua/ldebug.h
obj/lua/lundump.$(OBJ_EXT): src/lua/lundump.c  src/lua/ldo.h
obj/lua/lundump.$(OBJ_EXT): src/lua/lundump.c  src/lua/lfunc.h
obj/lua/lundump.$(OBJ_EXT): src/lua/lundump.c  src/lua/lmem.h
obj/lua/lundump.$(OBJ_EXT): src/lua/lundump.c  src/lua/lobject.h
obj/lua/lundump.$(OBJ_EXT): src/lua/lundump.c  src/lua/lprefix.h
obj/lua/lundump.$(OBJ_EXT): src/lua/lundump.c  src/lua/lstring.h
obj/lua/lundump.$(OBJ_EXT): src/lua/lundump.c  src/lua/lua.h
obj/lua/lundump.$(OBJ_EXT): src/lua/lundump.c  src/lua/lundump.h
obj/lua/lundump.$(OBJ_EXT): src/lua/lundump.c  src/lua/lzio.h
obj/lua/lundump.h: src/lua/lundump.h  src/lua/llimits.h
obj/lua/lundump.h: src/lua/lundump.h  src/lua/lobject.h
obj/lua/lundump.h: src/lua/lundump.h  src/lua/lzio.h
obj/lua/lutf8lib.$(OBJ_EXT): src/lua/lutf8lib.c  src/lua/lauxlib.h
obj/lua/lutf8lib.$(OBJ_EXT): src/lua/lutf8lib.c  src/lua/lprefix.h
obj/lua/lutf8lib.$(OBJ_EXT): src/lua/lutf8lib.c  src/lua/lua.h
obj/lua/lutf8lib.$(OBJ_EXT): src/lua/lutf8lib.c  src/lua/lualib.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/ldebug.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/ldo.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/lfunc.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/lgc.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/lobject.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/lopcodes.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/lprefix.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/lstate.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/lstring.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/ltable.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/ltm.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/lua.h
obj/lua/lvm.$(OBJ_EXT): src/lua/lvm.c  src/lua/lvm.h
obj/lua/lvm.h: src/lua/lvm.h  src/lua/ldo.h
obj/lua/lvm.h: src/lua/lvm.h  src/lua/lobject.h
obj/lua/lvm.h: src/lua/lvm.h  src/lua/ltm.h
obj/lua/lzio.$(OBJ_EXT): src/lua/lzio.c  src/lua/llimits.h
obj/lua/lzio.$(OBJ_EXT): src/lua/lzio.c  src/lua/lmem.h
obj/lua/lzio.$(OBJ_EXT): src/lua/lzio.c  src/lua/lprefix.h
obj/lua/lzio.$(OBJ_EXT): src/lua/lzio.c  src/lua/lstate.h
obj/lua/lzio.$(OBJ_EXT): src/lua/lzio.c  src/lua/lua.h
obj/lua/lzio.$(OBJ_EXT): src/lua/lzio.c  src/lua/lzio.h
obj/lua/lzio.h: src/lua/lzio.h  src/lua/lmem.h
obj/lua/lzio.h: src/lua/lzio.h  src/lua/lua.h
obj/lua_rtns.$(OBJ_EXT): src/lua_rtns.cpp  inc/lua_rtns.h
obj/lua_rtns.$(OBJ_EXT): src/lua_rtns.cpp  inc/oppat.h
obj/lua_rtns.$(OBJ_EXT): src/lua_rtns.cpp  inc/perf_event_subset.h
obj/lua_rtns.$(OBJ_EXT): src/lua_rtns.cpp  inc/printf.h
obj/lua_rtns.$(OBJ_EXT): src/lua_rtns.cpp  inc/rd_json.h
obj/lua_rtns.$(OBJ_EXT): src/lua_rtns.cpp  inc/rd_json2.h
obj/lua_rtns.$(OBJ_EXT): src/lua_rtns.cpp  inc/utils.h
obj/lua_rtns.$(OBJ_EXT): src/lua_rtns.cpp  inc/utils2.h
obj/mygetopt.$(OBJ_EXT): src/mygetopt.c  inc/mygetopt.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/MemoryMapped.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/ck_nesting.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/dump.hpp
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/etw_parse.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/lua_rtns.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/mygetopt.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/oppat.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/perf_event_subset.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/prf_read_data.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/printf.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/rd_json.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/rd_json2.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/tc_read_data.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/utils.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/utils2.h
obj/oppat.$(OBJ_EXT): src/oppat.cpp  inc/web_api.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/MemoryMapped.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/ck_nesting.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/dump.hpp
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/lua_rtns.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/mygetopt.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/oppat.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/perf_event_subset.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/prf_read_data.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/printf.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/rd_json.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/rd_json2.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/tc_read_data.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/utils.h
obj/prf_read_data.$(OBJ_EXT): src/prf_read_data.cpp  inc/web_api.h
obj/printf.$(OBJ_EXT): src/printf.cpp  inc/printf.h
obj/pugixml.$(OBJ_EXT): src/pugixml.cpp  inc/pugixml.hpp
obj/rd_json.$(OBJ_EXT): src/rd_json.cpp  inc/json.hpp
obj/rd_json.$(OBJ_EXT): src/rd_json.cpp  inc/rd_json.h
obj/rd_json.$(OBJ_EXT): src/rd_json.cpp  inc/rd_json2.h
obj/rd_json.$(OBJ_EXT): src/rd_json.cpp  inc/utils.h
obj/rd_json.$(OBJ_EXT): src/rd_json.cpp  inc/utils2.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/MemoryMapped.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/ck_nesting.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/dump.hpp
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/lua_rtns.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/mygetopt.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/oppat.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/perf_event_subset.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/prf_read_data.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/printf.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/rd_json.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/rd_json2.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/tc_read_data.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/utils.h
obj/tc_read_data.$(OBJ_EXT): src/tc_read_data.cpp  inc/web_api.h
obj/utils.$(OBJ_EXT): src/utils.cpp  inc/utils.h
obj/utils2.$(OBJ_EXT): src/utils2.cpp  inc/utils.h
obj/utils2.$(OBJ_EXT): src/utils2.cpp  inc/utils2.h
obj/web_api.$(OBJ_EXT): src/web_api.cpp  inc/web_api.h
obj/win_msr.$(OBJ_EXT): src/win_msr.c  inc/OlsApiInit.h
obj/win_msr.$(OBJ_EXT): src/win_msr.c  inc/OlsDef.h
obj/win_msr.$(OBJ_EXT): src/win_msr.c  inc/utils.h
obj/win_msr.$(OBJ_EXT): src/win_msr.c  inc/win_msr.h
